#api call for listing employees
###
GET http://127.0.0.1:8000/employees/
Accept: application/json


#api call for creating employees
###
POST http://127.0.0.1:8000/employees/
Content-Type: application/json

{
    "name":"Ajmal",
    "department":"sales",
    "salary":6000,
    "location":"pkd",
    "email":"ajmal@gmail.com"
}


#api call for retrive employee
###
GET http://127.0.0.1:8000/employees/1
Accept: application/json


#api call for delete employee
###
DELETE  http://127.0.0.1:8000/employees/2
Accept: application/json

#api call for updating employee
###
PUT http://127.0.0.1:8000/employees/1
Content-Type: application/json

{
    "name":"Arun",
    "department":"hr",
    "salary":6000,
    "location":"tvm",
    "email":"arun@gmail.com"
}